travis:
  secure:
    BINSTAR_TOKEN: fpNmjBj+7Szvd59Hp/X4xIGoHVzS3BA4gNqBkHTYPe31acQSgv1DThAwL0/YPEx8o32ZDuyV5qooCn9WOXzfaL5B5qhMutp+Nodqvz4WdclEU1sxbu1VStLLfej6A7w9udugvCmghNyRQcBC4xj+xa1O5ju0GLU1aqsq3eM3MWYhMLgQ+dpJQ5meKC+JmDNSJGsiGvKtvjEuMtYVFAQsvGZnmCdVW2LCMvq/8YOWcKqHx5txrMnyMTko1DCnvbqsrEmnaAYr8c4mR9+jdxR4mEcNxJeBSRuyfYL+A/FS1Y1pofTirUaVQTplp7H6sIYOrm7rvh1LnJg+Kam9ACNequ/5TTMNhZZmSdz2pqk6Ov/UhowZ6pA5P4KBlJSEupv53CK1aR0CX2X15btJFQ6b1Ljx2wxusnVzD6qqjZweuLgI6zvuVJdTB0GjL3yf66iDl5/vtwhFDJGhhE3xmW6S2NfeHCrR+B9+Jn90U3Y8mq1yRP+grrNVb2Vz3QnlvmERFtERUx4iHcTVs+q7qIyZI1bv5QQMKbukZO/5dHftJcP97wcDiCeR2AqB3h5X/Y2OkFnMPpREBX+acWQv+gBRUOqNBJl8MTmdW28gORaXvxc23VXNBOewFw/bULCJYFaMgMm0tWg5S7SKJKIYXpCSIU6brYesRCnk17Emr4q61n8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
