travis:
  secure:
    BINSTAR_TOKEN: R9o7Q7kWU+dqSFENQZaWbfn28NpjV68v09co+8h9gRv3v6tDIlvQ+muz0LDMlhwmi2bwpHjDW74obt8fILelzL5Skigq+VxmzIUYorEjrtv9aFZZ1Mjq8lUWhKG0DbquNFP0NtPWWspNASqzb9nYPUGbxFWwwNMs8pUQ5rJaFp5dSA7ErZDXUA4/m+Es7gSOWHiLrBv6YimVMYQtbSV7FU6+7ozrBYQlwwR1XSyO22iEpy6w6XIhnB43X6gwBUSjhKBq8SNCoIcct4NI7It/dkFJrbgzR8BS0hrui/gS2/XAaxEqjH8Dt3E/eSgePqI8yCyfkud3DQY5QJv9tJs8meAWd+/cmsWmpvEJq6EgyYoxnsyI8WEuFRadcpNUQfdcONVVzc2ECk3pQq6wy2wvYZ97lGfq99jhOPPZOhi5CaxbRAawEzp3BXlb3q4qyzZDyvR4/knpCKgYCE1+epemQUEDIhjQM0gM7zcP4xyaiOc3xUf9eRnX4eC4yEwaFXrY2uYW4aKHJZIN2GiLaoF+KOcwbTUKkxf5J9q6HEsrLoNQ1GK8ZvLUhbARcEPfHCFi6g10bnFCA57H/PE6fmisoNL2CCXhYUcn2418LkXnfo3Ft1CDyyyyXZCOohNsnG8b5mAfWi5cooGLMDoxE3lZo8yiLxuLjhhHyT1dhrHcXO8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
